#!/usr/bin/env bash
# This script tells the story of users from /etc/passwd using while loop and IFS

while IFS=: read -r username password uid gid full_name home shell; do
  echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $full_name"
done < /etc/passwd
